---
- name: Install my tools on Ubuntu
  hosts: latrobe
  become: yes
  tasks:
    - name: install misc tools
      apt:
        name: 
        - athena-jot
        - htop
        - fortune
        - cowsay
        - lolcat
        - apcalc
        - ipcalc
        - figlet
        - toilet
        - ascii-banner
        state: present