- name: Start Azure VM
  hosts: latrobe
  connection: local
  
  vars:
    azure_resource_group: RGVMAUEGRx
    azure_vm_name: vmlatrobeausubux

  tasks:
    - name: Start the virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_vm_name }}"
        started: yes
